export const ACTIONS = {
  ADJUST_TEXTSIZE: 'ADJUST_TEXTSIZE',
  CHANGE_TITLE: 'CHANGE_TITLE',
  RECEIVE_SERVICE: 'RECEIVE_SERVICE',
  REQUEST_SERVICE: 'REQUEST_SERVICE',
  TOGGLE_SERVICE: 'SHOW_SERVICE',
  TOGGLE_SETTINGS: 'TOGGLE_SETTINGS',
  TOGGLE_LANGUAGE: 'TOGGLE_LANGUAGE'
}
